	<section id="noticias">
		<div class="enfeite">
			<div class="enf_top_esq"></div>
			<div class="enf_top_dir"></div>
		</div>
		<h2>ÚLTIMAS NOTÍCIAS:</h2>
		<div class="enfeite">
			<div class="enf_bot_esq"></div>
			<div class="enf_bot_dir"></div>
		</div>
		<section>
			<h2>Ainda não temos notícias cadastradas.</h2>
<!-- 			<p><span>12/Set</span>Hoje fui experimentar o vestido de noiva.</p> -->
<!-- 			<div class="sep"></div>
			<h2>12/Set</h2>
			<p><span>12/Set</span>Hoje fui experimentar o vestido de noiva.</p>
			<div class="sep"></div>
			<h2>12/Set</h2>
			<p><span>12/Set</span>Hoje fui experimentar o vestido de noiva.</p> -->
		</section>
	</section>