	<section id="frases">
		<div class="enfeite">
			<div class="enf_top_esq"></div>
			<div class="enf_top_cen"></div>
			<div class="enf_top_dir"></div>
		</div>

		<h2>Um sonho que se vive sozinho é apenas um sonho. Um sonho que se vive à dois é uma realidade.<span>William Shakespeare</span></h2>

		<div class="enfeite">
			<div class="enf_bot_esq"></div>
			<div class="enf_bot_cen"></div>
			<div class="enf_bot_dir"></div>
		</div>
	</section>