	<section id="ultimas">
		<div clas="enfeite_cima"><div clas="enf_cima_01"><img src="<?php include_once($_SERVER['DOCUMENT_ROOT']."/_templates/001/link_enf_cima_01.png"); ?>"></div><div clas="enf_cima_02"><img src="<?php include_once($_SERVER['DOCUMENT_ROOT']."/_templates/001/link_enf_cima_02.png"); ?>"></div><div clas="enf_cima_03"><img src="<?php include_once($_SERVER['DOCUMENT_ROOT']."/_templates/001/link_enf_cima_03.png"); ?>"></div></div>

		<h2>Últimas notícias:</h2>

		<div clas="enfeite_baixo"><div clas="enf_baixo_01"><img src="<?php include_once($_SERVER['DOCUMENT_ROOT']."/_templates/001/link_enf_baixo_01.png"); ?>"></div><div clas="enf_baixo_02"><img src="<?php include_once($_SERVER['DOCUMENT_ROOT']."/_templates/001/link_enf_baixo_02.png"); ?>"></div><div clas="enf_baixo_03"><img src="<?php include_once($_SERVER['DOCUMENT_ROOT']."/_templates/001/link_enf_baixo_03.png"); ?>"></div></div>

		<div class="ultimas inicio">
<!-- 			<h2>12/Set</h2> -->
			<p>Ainda não temos notícias cadastradas.</p>
		</div>
<!-- 		<div class="ultimas">
			<h2>12/Set</h2>
			<p>Hoje fui experimentar o vestido de noiva.</p>
		</div>
		<div class="ultimas final">
			<h2>12/Set</h2>
			<p>Hoje fui experimentar o vestido de noiva.</p>
		</div> -->
	</section>