	<section id="noivos_mini">
		<a href="noivos.php#noiva" title="Aline">
			<div class="foto">
				<img src="fotos/link_noiva.jpg" alt="Aline" />
			</div>
			<div class="dados">
				<h2>Aline</h2>
				<p>22 Anos</p>
				<p>É de gêmeos, gosta de estudar, de um bom shopping, não consegue parar um minuto e tem um gênio beeeeeeem difícil de lidar.</p>
			</div>
		</a>
		<a href="noivos.php#noivo" title="Diogo">
			<div class="foto">
				<img src="fotos/link_noivo.jpg" alt="Diogo" />
			</div>
			<div class="dados">
				<h2>Diogo</h2>
				<p>25 Anos</p>
				<p>É de câncer, gosta de dormir, de animais, vibra pelo Palmeiras, troca tudo por um cinema e odeia estudar.</p>
			</div>
		</a>
	</section>