	<section id="galeria">
		<div>
			<img src="fotos/link_banner_peq_001.jpg" alt="Aline &amp; Diogo" class="mobile active" />
			<img src="fotos/link_banner_peq_002.jpg" alt="Aline &amp; Diogo" class="mobile noscript" />
			<img src="fotos/link_banner_peq_003.jpg" alt="Aline &amp; Diogo" class="mobile noscript" />
			<img src="fotos/link_banner_001.jpg" alt="Aline &amp; Diogo" class="desktop active" />
			<img src="fotos/link_banner_002.jpg" alt="Aline &amp; Diogo" class="desktop noscript" />
			<img src="fotos/link_banner_003.jpg" alt="Aline &amp; Diogo" class="desktop noscript" />
		</div>
	</section>